---

- name: Check existence of atuin systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ atuin_identifier }}.service"
  register: atuin_service_stat

- when: atuin_service_stat.stat.exists | bool
  block:
    - name: Ensure atuin service is stopped
      ansible.builtin.service:
        name: "{{ atuin_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure atuin service doesn't exist
      ansible.builtin.file:
        dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ atuin_identifier }}.service"
        state: absent

    - name: Ensure atuin base path is files deleted (make sure to delete node data)
      ansible.builtin.file:
        path: "{{ atuin_base_path }}"
        state: absent
