---

- name: Fail if required atuin settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) for using this role.
  when: "vars[item] == ''"
  with_items:
    - atuin_hostname
    - atuin_uid
    - atuin_gid
    - atuin_database_host
    - atuin_database_username
    - atuin_database_password

# Removed SMTP or traefik check
